wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.13
    start_time: 1635048273
    t:
      1:
      - 1
      4: 3.6.13
      5: 0.12.1
      8:
      - 2
      - 3
      - 5
